### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by iPocket**
Seriously?

### CODE REVIEW

**Comment by remotevase** [comment]
honestly, I dont even know what this is, and who created it. Not my responsibility, therefore, I will not do anything about this

**Comment by remotevase** [comment]
nver mind, it appears that 
@Taki21 (the **PHP PROFESSOR**) made a mistake that only the noobiest of noobs could make
:/

**Comment by HimbeersaftLP** [comment]
> nver mind, it appears that 
@Taki21 (the PHP PROFESSOR) made a mistake that only the noobiest of noobs could make
 :/

Maybe Noob Taki kidnapped the real Taki21... We have to search him!

**Comment by remotevase** [comment]
well, @HimbeersaftLP that appears to be the only logical explanation! Hmm, maybe I should go over to takis house later and check on him. Then I will go and check if any new flavors of taki chips are being made (that would be delicious). If he is not in his house, and if he is not making new taki flavors, then... the last resort... Me and taki's secret warehouse in albany...

**Comment by HimbeersaftLP** [comment]
LOL

**Comment by iPocket** [comment]
HimbeersaftLP: I tried to not say "LOL" for spam, so I used a reaction instead, so you might too....

**Comment by remotevase** [comment]
who cares about spam? Not me!

**Comment by remotevase** [comment]
I

**Comment by remotevase** [comment]
am

**Comment by remotevase** [comment]
Correction:

**Comment by remotevase** [comment]
I

**Comment by remotevase** [comment]
love

**Comment by remotevase** [comment]
spamming

**Comment by remotevase** [comment]
lots

**Comment by remotevase** [comment]
and

**Comment by remotevase** [comment]
lots

**Comment by remotevase** [comment]
of

**Comment by remotevase** [comment]
persons

**Comment by remotevase** [comment]
AKA

**Comment by remotevase** [comment]
lots

**Comment by remotevase** [comment]
and

**Comment by iPocket** [comment]
...

**Comment by remotevase** [comment]
lots

**Comment by remotevase** [comment]
of

**Comment by remotevase** [comment]
people

**Comment by iPocket** [comment]
well

**Comment by iPocket** [comment]
stop...

**Comment by remotevase** [comment]
:)

**Comment by remotevase** [comment]
ok

**Comment by Taki21** [comment]
download

**Comment by Taki21** [comment]
The whole point:
https://www.youtube.com/watch?v=ZBxWgkIJSGU

**Comment by TheKnightGamer** [comment]
Brah

**Pull request merged**
